---
vars:
  mode: ${MODE}

default:
  td:
    project:
      performOnStart: False
    ui:
      performMode: False
  vars:
    RESX: 2160
    RESY: 3840
    assets_path: ${ASSETS_PATH}
    comfyui_url: ${COMFYUI_URL}
    comfyui_inputs_dir: ${COMFYUI_INPUTS_DIR}
    comfyui_outputs_dir: ${COMFYUI_OUTPUTS_DIR}
    monitor_index: ${MONITOR_INDEX}
    blackmagic_camera_index: ${BLACKMAGIC_CAMERA_INDEX}
    takeaway_render_dir: ${TAKEAWAYS_RENDER_DIR}
    headless: False
  ops:
    '/project1/output':
      par:
        Devresscale:
          val: 1
    '/tools/perf_logs':
      par:
        Enabled:
          val: False
        # log performance every minute
        Loginterval:
          val: 60
    '/tools/console_clear':
      par:
        Enabled:
          val: False
        # clear the console every hour minute
        Interval:
          val: 3600

dev:
  td:
    ui:
      performMode: False
  vars:
    devVar: 123

production:
  td:
    project:
      performOnStart: True
    ui:
      performMode: True
  ops:
    '/tools/perf_logs':
      par:
        Enabled:
          val: True
        # log performance every minute
        Loginterval:
          val: 60
    '/tools/console_clear':
      par:
        Enabled:
          val: True
        # clear the console every hour minute
        Interval:
          val: 3600
